version: '3.8'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqubemule
    ports:
      - "9000:9000"
    environment: 
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    networks:
      - dev-net

volumes:
  sonarqube_data:

networks:
  dev-net:
    external: true
